name: Cleanup

on:
  schedule:
    - cron: '0 7 * * *'

jobs:
  cleanup:
    runs-on: ubuntu-latest

    steps:
    - name: Run cleanup task
      run: |
        # Add your cleanup script here
        echo "Running cleanup task"
      env:
        CLEANUP_API_KEY: ${{ secrets.CLEANUP_API_KEY }}
        